export const FETCHING_INIT_DATA = "FETCHING_INIT_DATA";
export const RECEIVED_INIT_DATA = "RECEIVED_INIT_DATA";
export const CHANGE_BOARD_TO_ALLTIME = "CHANGE_BOARD_TO_ALLTIME";
export const CHANGE_BOARD_TO_DAY = "CHANGE_BOARD_TO_DAY";
export const CHANGE_BOARD_TO_WEEK = "CHANGE_BOARD_TO_WEEK";
export const CHANGE_BOARD_TO_MONTH = "CHANGE_BOARD_TO_MONTH";
